FROM tomcat
WORKDIR /root/boxfuse
RUN apt update; \
    apt -y install maven; \
    git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /root/boxfuse; \
    mvn package  ; \
    cp target/hello-1.0.war /usr/local/tomcat/webapps/
